#!/usr/bin/env python3
"""
MEMORY.md consolidation pass (#4) — keep the always-loaded index under budget.

MEMORY.md loads into EVERY session, so it has a line budget (~200). Auto-generated
lessons accumulate one verbose index line each ("auto-generated from ratings data"
×N) — low signal, and redundant now that FailurePatternReminder injects the lesson
files directly when task-relevant. This pass:

  1. Collapses the N `- [Auto-lesson: X](lesson_autogen_X.md)` lines into ONE
     compact line that still lists the pattern names (recall-friendly).
  2. Reports autogen lessons that duplicate a hand-written feedback memory
     (keyword overlap) — REPORT ONLY, never auto-deletes hand-written memory.
  3. Reports the line budget.

SAFE: never deletes lesson files; backs up MEMORY.md before writing; idempotent
(re-running after collapse is a no-op); dry-run is the default.

Usage:
  python consolidate_memory.py            # dry-run: print diff + report, write nothing
  python consolidate_memory.py --apply    # back up MEMORY.md.bak, then write
"""

from __future__ import annotations

import argparse
import difflib
import re
from pathlib import Path

MEMORY_DIR = Path.home() / ".claude/MEMORY/lessons"
MEMORY_MD = MEMORY_DIR / "MEMORY.md"
BUDGET = 200

AUTOGEN_RE = re.compile(r"^- \[Auto-lesson:[^\]]*\]\((lesson_autogen_[^)]+\.md)\)")
COLLAPSED_RE = re.compile(r"^- \[Auto-lessons \(\d+\)\]")


def tokens(s: str) -> set[str]:
    return {w for w in re.split(r"[^a-z]+", s.lower()) if len(w) > 3}


def find_duplicates(patterns: list[str]) -> list[tuple[str, str]]:
    """autogen pattern ↔ hand-written feedback memory with strong keyword overlap."""
    hand = [f for f in MEMORY_DIR.glob("*.md")
            if not f.name.startswith("lesson_autogen_") and f.name not in ("MEMORY.md",)]
    dups = []
    for p in patterns:
        ptoks = tokens(p.replace("_", " "))
        for f in hand:
            ftoks = tokens(f.stem.replace("_", " "))
            overlap = ptoks & ftoks
            if len(overlap) >= 2:  # ≥2 shared meaningful tokens → likely same concept
                dups.append((p, f.name))
    return dups


def consolidate(text: str) -> tuple[str, dict]:
    lines = text.split("\n")
    # Disk is the source of truth — regenerate from the actual lesson files so the
    # line auto-reflects new patterns and never drifts from what's on disk.
    patterns = sorted(p.stem.replace("lesson_autogen_", "")
                      for p in MEMORY_DIR.glob("lesson_autogen_*.md"))
    # Remove every existing representation: individual lines AND any prior collapsed line.
    remove_idx = [i for i, l in enumerate(lines) if AUTOGEN_RE.match(l) or COLLAPSED_RE.match(l)]
    already = any(COLLAPSED_RE.match(l) for l in lines)

    info = {"autogen_count": sum(1 for l in lines if AUTOGEN_RE.match(l)),
            "already_collapsed": already, "before_lines": len(lines),
            "patterns": patterns, "duplicates": find_duplicates(patterns)}

    if not patterns or not remove_idx:
        info["after_lines"] = len(lines)
        return text, info

    rep = f"lesson_autogen_{patterns[0]}.md"
    names = ", ".join(patterns)
    # Invisible HTML comment lists every filename so self_improve.update_memory_index's
    # `filename in content` check passes → it never re-appends individual lines (no churn).
    filerefs = " ".join(f"lesson_autogen_{p}.md" for p in patterns)
    collapsed = (f"- [Auto-lessons ({len(patterns)})]({rep}) — {names}; "
                 f"auto-generated by self_improve.py, injected by FailurePatternReminder when task-relevant "
                 f"<!-- {filerefs} -->")

    insert_at, drop = remove_idx[0], set(remove_idx)
    out = []
    for i, l in enumerate(lines):
        if i == insert_at:
            out.append(collapsed)
        elif i in drop:
            continue
        else:
            out.append(l)

    new_text = "\n".join(out)
    info["after_lines"] = len(out)
    return new_text, info


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="back up + write (default: dry-run)")
    args = ap.parse_args()

    if not MEMORY_MD.exists():
        print(f"MEMORY.md not found at {MEMORY_MD}")
        return 1

    original = MEMORY_MD.read_text()
    new_text, info = consolidate(original)

    print(f"Lines: {info['before_lines']} → {info['after_lines']} (budget {BUDGET})")
    print(f"Autogen index lines collapsed: {info['autogen_count']}")
    if info["already_collapsed"] and info["autogen_count"] == 0:
        print("Already consolidated — nothing to do.")
    over = info["after_lines"] - BUDGET
    print(f"Budget: {'OK' if over <= 0 else f'OVER by {over} lines'}")

    if info["duplicates"]:
        print("\nPossible duplicates (autogen ↔ hand-written) — review manually, NOT auto-removed:")
        for p, f in info["duplicates"]:
            print(f"  • lesson_autogen_{p}  ~  {f}")

    if new_text == original:
        print("\nNo changes.")
        return 0

    diff = difflib.unified_diff(original.split("\n"), new_text.split("\n"),
                               "MEMORY.md (before)", "MEMORY.md (after)", lineterm="")
    print("\n--- diff ---")
    print("\n".join(diff))

    if not args.apply:
        print("\n[dry-run] no files written. Re-run with --apply to commit.")
        return 0

    backup = MEMORY_MD.with_suffix(".md.bak")
    backup.write_text(original)
    MEMORY_MD.write_text(new_text)
    print(f"\nBacked up → {backup}")
    print(f"Wrote → {MEMORY_MD} ({info['after_lines']} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
