"""Keep the always-loaded MEMORY.md lesson index within a bounded line budget.

The consolidator replaces individual generated-lesson index rows with one compact,
idempotent row. It never deletes lesson files or handwritten memory, and an apply
runs under the same sidecar lock used by self-improvement index updates.
"""

from __future__ import annotations

import argparse
import difflib
import re
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import cast

from harness_paths import HARNESS_HOME
from state_io import atomic_write_text, exclusive_lock

MEMORY_DIR = HARNESS_HOME / "MEMORY/lessons"
MEMORY_MD = MEMORY_DIR / "MEMORY.md"
BUDGET = 200

AUTOGEN_RE = re.compile(r"^- \[Auto-lesson:[^\]]*\]\((lesson_autogen_[^)]+\.md)\)")
COLLAPSED_RE = re.compile(r"^- \[Auto-lessons \(\d+\)\]")


def tokens(value: str) -> set[str]:
    return {word for word in re.split(r"[^a-z]+", value.lower()) if len(word) > 3}


def find_duplicates(
    patterns: list[str], memory_dir: Path | None = None
) -> list[tuple[str, str]]:
    """Return generated patterns with strong filename overlap to handwritten memory."""
    directory = memory_dir or MEMORY_DIR
    try:
        hand = [
            path
            for path in directory.glob("*.md")
            if path.name != "MEMORY.md"
            and not path.name.startswith("lesson_autogen_")
            and path.is_file()
            and not path.is_symlink()
        ]
    except OSError:
        return []
    duplicates: list[tuple[str, str]] = []
    for pattern in patterns:
        pattern_tokens = tokens(pattern.replace("_", " "))
        for path in hand:
            overlap = pattern_tokens & tokens(path.stem.replace("_", " "))
            if len(overlap) >= 2:
                duplicates.append((pattern, path.name))
    return duplicates


def discover_patterns(memory_dir: Path) -> list[str]:
    try:
        paths = memory_dir.glob("lesson_autogen_*.md")
        return sorted(
            path.stem.removeprefix("lesson_autogen_")
            for path in paths
            if path.is_file() and not path.is_symlink()
        )
    except OSError:
        return []


def consolidate(text: str, memory_dir: Path | None = None) -> tuple[str, dict[str, object]]:
    directory = memory_dir or MEMORY_DIR
    lines = text.split("\n")
    patterns = discover_patterns(directory)
    remove_idx = [
        index
        for index, line in enumerate(lines)
        if AUTOGEN_RE.match(line) or COLLAPSED_RE.match(line)
    ]
    already = any(COLLAPSED_RE.match(line) for line in lines)
    info: dict[str, object] = {
        "autogen_count": sum(1 for line in lines if AUTOGEN_RE.match(line)),
        "already_collapsed": already,
        "before_lines": len(lines),
        "patterns": patterns,
        "duplicates": find_duplicates(patterns, directory),
    }
    if not patterns or not remove_idx:
        info["after_lines"] = len(lines)
        return text, info

    representative = f"lesson_autogen_{patterns[0]}.md"
    names = ", ".join(patterns)
    file_refs = " ".join(f"lesson_autogen_{pattern}.md" for pattern in patterns)
    collapsed = (
        f"- [Auto-lessons ({len(patterns)})]({representative}) — {names}; "
        "auto-generated by self_improve.py, injected by FailurePatternReminder "
        f"when task-relevant <!-- {file_refs} -->"
    )

    insert_at = remove_idx[0]
    dropped = set(remove_idx)
    output: list[str] = []
    for index, line in enumerate(lines):
        if index == insert_at:
            output.append(collapsed)
        elif index not in dropped:
            output.append(line)
    new_text = "\n".join(output)
    info["after_lines"] = len(output)
    return new_text, info


def backup_path(path: Path) -> Path:
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
    return path.with_name(f"{path.name}.bak.{timestamp}.{uuid.uuid4().hex[:8]}")


def print_report(original: str, new_text: str, info: dict[str, object]) -> None:
    before_lines = cast(int, info["before_lines"])
    after_lines = cast(int, info["after_lines"])
    print(f"Lines: {before_lines} → {after_lines} (budget {BUDGET})")
    print(f"Autogen index lines collapsed: {info['autogen_count']}")
    if info["already_collapsed"] and info["autogen_count"] == 0:
        print("Already consolidated — nothing to do.")
    over = after_lines - BUDGET
    print(f"Budget: {'OK' if over <= 0 else f'OVER by {over} lines'}")

    duplicates = info.get("duplicates")
    if isinstance(duplicates, list) and duplicates:
        print("\nPossible duplicates (autogen ↔ hand-written) — review manually, NOT auto-removed:")
        for pattern, filename in duplicates:
            print(f"  • lesson_autogen_{pattern}  ~  {filename}")

    if new_text == original:
        print("\nNo changes.")
        return
    diff = difflib.unified_diff(
        original.split("\n"),
        new_text.split("\n"),
        "MEMORY.md (before)",
        "MEMORY.md (after)",
        lineterm="",
    )
    print("\n--- diff ---")
    print("\n".join(diff))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--apply", action="store_true", help="back up + write (default: dry-run)")
    args = parser.parse_args(argv)

    if not MEMORY_MD.exists() or not MEMORY_MD.is_file() or MEMORY_MD.is_symlink():
        print(f"MEMORY.md not found or unsafe at {MEMORY_MD}")
        return 1

    if not args.apply:
        try:
            original = MEMORY_MD.read_text()
        except OSError as exc:
            print(f"Unable to read MEMORY.md: {exc}")
            return 1
        new_text, info = consolidate(original, MEMORY_DIR)
        print_report(original, new_text, info)
        if new_text != original:
            print("\n[dry-run] no files written. Re-run with --apply to commit.")
        return 0

    try:
        with exclusive_lock(MEMORY_MD):
            original = MEMORY_MD.read_text()
            new_text, info = consolidate(original, MEMORY_DIR)
            print_report(original, new_text, info)
            if new_text == original:
                return 0
            backup = backup_path(MEMORY_MD)
            atomic_write_text(backup, original)
            try:
                atomic_write_text(MEMORY_MD, new_text)
            except BaseException:
                atomic_write_text(MEMORY_MD, original)
                raise
    except (OSError, TimeoutError) as exc:
        print(f"Unable to consolidate MEMORY.md: {exc}")
        return 1

    print(f"\nBacked up → {backup}")
    print(f"Wrote → {MEMORY_MD} ({info['after_lines']} lines)")
    return 0


if __name__ == "__main__":  # pragma: no cover - exercised by install smoke tests
    raise SystemExit(main())
