#!/usr/bin/env python3
"""
enforcement_promotion.py — graduation path for CONFIG-ONLY enforcement patterns.

measure_effectiveness.py's escalation pipeline only covers patterns that (a) have an
autogenerated lesson file (lesson_autogen_<pattern>.md) and (b) are driven by
ratings.jsonl's 1-10 subjective scores via self_improve.classify_entry. Patterns like
`graphiti_bypassed` in EnforcementGate.hook.ts don't fit that shape at all — there's no
lesson, no user rating tied to a single turn, just a mechanical tool-use-name check whose
mode (warn/block) is read directly from enforcement_config.json overrides. Wiring a
mechanical detector into the rating-based pipeline would be dishonest curve-fitting (it
would report the WRONG signal as "effectiveness").

This script is the parallel, honest measurement for that class of pattern: it reads
enforcement_log.jsonl directly (the actual fire history of the hook, not proxied through
ratings), and if a warn-mode pattern fires often enough in the trailing window, queues it
for HUMAN review via the SAME pending_human_review.jsonl queue review_queue.py already
manages — no auto-promotion to block without a human approving it. This preserves the
existing "human in the loop before hard enforcement" principle uniformly across both
pipelines instead of adding a silent self-promoting path.

On --approve (via review_queue.py, extended to detect config-only patterns), the promotion
mechanically flips enforcement_config.json overrides[pattern] = "block" directly — for
these patterns THAT edit is what actually changes hook behavior (there is no escalate[]
consumer for them, unlike the lesson-driven patterns).

CONFIG_ONLY_PATTERNS: patterns whose EnforcementGate check reads its mode from
enforcement_config.json overrides only (not via the lesson/DETECTORS/escalate[] path).
Extend this set as more mechanical (non-lesson) checks are added to the hook.

Usage:
  python3 enforcement_promotion.py            # scan + queue candidates crossing threshold
  python3 enforcement_promotion.py --dry-run  # print what would be queued, write nothing
  python3 enforcement_promotion.py --window-days 14 --min-fires 5
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from datetime import datetime, timedelta, timezone
from pathlib import Path

ENFORCE_LOG   = Path.home() / ".claude/MEMORY/LEARNING/enforcement_log.jsonl"
CONFIG_JSON   = Path.home() / ".claude/MEMORY/STATE/enforcement_config.json"
REVIEW_FILE   = Path.home() / ".claude/MEMORY/LEARNING/SIGNALS/pending_human_review.jsonl"

# Patterns whose mode is read directly from enforcement_config.json overrides in
# EnforcementGate.hook.ts, with NO lesson file and NO escalate[] consumer. Must be
# kept in sync with the hook — each entry here needs a matching `cfg.overrides[...]`
# read in the .ts file for promotion to actually take effect.
CONFIG_ONLY_PATTERNS = {"graphiti_bypassed"}

DEFAULT_WINDOW_DAYS = 14
DEFAULT_MIN_FIRES = 5   # fires within the window to trigger a review-queue candidate


def load_config() -> dict:
    if not CONFIG_JSON.exists():
        return {"enabled": True, "overrides": {}}
    try:
        return json.loads(CONFIG_JSON.read_text())
    except (json.JSONDecodeError, OSError):
        return {"enabled": True, "overrides": {}}


def load_enforcement_log() -> list[dict]:
    if not ENFORCE_LOG.exists():
        return []
    rows = []
    for line in ENFORCE_LOG.read_text().splitlines():
        if not line.strip():
            continue
        try:
            rows.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return rows


def load_review_queue() -> list[dict]:
    if not REVIEW_FILE.exists():
        return []
    records = []
    for line in REVIEW_FILE.read_text().splitlines():
        if not line.strip():
            continue
        try:
            records.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return records


def write_review_queue(records: list[dict]) -> None:
    REVIEW_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(REVIEW_FILE, "w") as f:
        for rec in records:
            f.write(json.dumps(rec) + "\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--window-days", type=int, default=DEFAULT_WINDOW_DAYS)
    ap.add_argument("--min-fires", type=int, default=DEFAULT_MIN_FIRES)
    args = ap.parse_args()

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    cutoff = datetime.now(timezone.utc) - timedelta(days=args.window_days)

    cfg = load_config()
    overrides = cfg.get("overrides", {})

    log_rows = load_enforcement_log()
    review_records = load_review_queue()
    already_queued = {r["pattern"] for r in review_records
                       if r.get("status") == "pending" and r.get("source") == "enforcement_promotion"}

    candidates = []
    for pattern in sorted(CONFIG_ONLY_PATTERNS):
        current_mode = overrides.get(pattern, "warn")
        if current_mode != "warn":
            continue  # already off or already block — nothing to promote
        if pattern in already_queued:
            continue  # already awaiting human review

        fires_in_window = 0
        total_fires = 0
        for row in log_rows:
            if row.get("pattern") != pattern:
                continue
            total_fires += 1
            try:
                ts = datetime.fromisoformat(row["ts"].replace("Z", "+00:00"))
            except (KeyError, ValueError):
                continue
            if ts >= cutoff:
                fires_in_window += 1

        if fires_in_window >= args.min_fires:
            candidates.append({
                "pattern": pattern,
                "fires_in_window": fires_in_window,
                "total_fires": total_fires,
                "window_days": args.window_days,
            })

    if not candidates:
        print(f"[enforcement_promotion] No config-only patterns crossed the "
              f"{args.min_fires}-fires/{args.window_days}-day threshold.")
        return 0

    print(f"[enforcement_promotion] {len(candidates)} candidate(s) for promotion review:")
    for c in candidates:
        print(f"  {c['pattern']}: {c['fires_in_window']} fires in last {c['window_days']}d "
              f"({c['total_fires']} all-time) — currently 'warn', queuing for review")

    if args.dry_run:
        print("[dry-run] no files written")
        return 0

    for c in candidates:
        review_records.append({
            "pattern": c["pattern"],
            "detected_at": today,
            "delta": None,           # not applicable — this queue entry isn't rating-driven
            "after_n": c["fires_in_window"],
            "obj_verdict": "n/a",
            "judge_verdict": "n/a",
            "status": "pending",
            "reviewed_at": None,
            "reviewer": None,
            "source": "enforcement_promotion",
            "note": f"{c['fires_in_window']} fires in {c['window_days']}d (warn mode). "
                    f"Approve to promote to 'block' in enforcement_config.json.",
        })
    write_review_queue(review_records)
    print(f"[enforcement_promotion] Queued {len(candidates)} pattern(s) in "
          f"pending_human_review.jsonl. Review with: python3 review_queue.py --list")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
